# Lab 7: Introduction to Pandas

Welcome to your first **Pandas** lab.

To begin, create a copy of this file using File -> Save as... and name the new file "Lab_7_LastName_FirstName.ipynb" using your last and first name.  Make sure to execute all the code cells in the notebook and that the outputs show in your report. *Two points are allocated for reading and running the code blocks*. Before submitting, remember to add a collaboration statement in this mark down indicating the contribution of each member. You may edit the template below:

- Group member 1 first name, last name & student id: contributions here
- Group member 2 first name, last name & student id: contributions here
- if applicable, Group member 3 first name, last name & student id: contributions here

Up to this point, you have been working with core Python tools such as:
- variables
- lists
- indexing
- loops
- conditionals
- functions

Those tools still matter. **Pandas does not replace Python.**  
Instead, it gives us a better tool for working with **table-shaped data** such as:
- CSV files
- spreadsheets
- lab measurements
- survey data
- plate reader output

In this lab, you will learn:
- what Pandas is
- what it is used for
- how to load CSV data
- how to inspect a DataFrame
- how to select columns and rows
- how to calculate simple summaries

# Using Pandas Examples

## Step 1: Import Pandas

Make sure you have pandas installed. If you installed Anaconda, pandas should have been installed automatically. If you are using another python package manager like pip, refer to the instructions at https://pandas.pydata.org/docs/getting_started/index.html for installation instructions.

Before we can use Pandas, we need to import it.

Run the cell below.

In [1]:
import pandas as pd

print("Pandas loaded successfully")

Pandas loaded successfully

## Step 2: What is Pandas?

Pandas is a Python library used to work with **tabular data**.

A Pandas table is called a **DataFrame**.

You can think of a DataFrame like:
- an Excel sheet
- a table with rows and columns
- a CSV file loaded into Python

## Step 3: Creating a Simple DataFrame

We can build a DataFrame from a Python dictionary.
Each key becomes a column.

In [2]:

lab_data = {
    "Sample": ["Control", "Treatment A", "Treatment B"],
    "Abs600": [0.62, 0.81, 0.77],
    "Replicate": [1, 1, 1]
}

df = pd.DataFrame(lab_data)
print(df)

        Sample  Abs600  Replicate
0      Control    0.62          1
1  Treatment A    0.81          1
2  Treatment B    0.77          1

### What happened?

We created a DataFrame named `df`.

Notice:
- column names are at the top
- each horizontal line is a row
- each row stores one observation

## Step 4: Viewing the First Rows

A common beginner function is:

```python
df.head()
```

This shows the first 5 rows by default.

In [3]:
df.head()

        Sample  Abs600  Replicate
0      Control    0.62          1
1  Treatment A    0.81          1
2  Treatment B    0.77          1

## Step 5: Inspecting Basic Information

When you first load a dataset, you usually want to ask:
- how many rows and columns are there?
- what are the column names?
- what type of object is this?

In [4]:

print("Type:", type(df))
print("Shape:", df.shape)
print("Columns:", df.columns)

Type: <class 'pandas.core.frame.DataFrame'>
Shape: (3, 3)
Columns: Index(['Sample', 'Abs600', 'Replicate'], dtype='object')

### Vocabulary

- `DataFrame` = a table of data
- `shape` = number of rows and columns
- `columns` = column names

## Step 6: Selecting One Column

To select one column, use:

```python
df["column_name"]
```

This returns a **Series**, which is like one column of values.

In [5]:
print(df["Abs600"])

0    0.62
1    0.81
2    0.77
Name: Abs600, dtype: float64

## Step 7: Selecting More Than One Column

Use a list of column names inside double square brackets.

In [6]:
print(df[["Sample", "Abs600"]])

        Sample  Abs600
0      Control    0.62
1  Treatment A    0.81
2  Treatment B    0.77

## Step 8: Selecting Rows with `iloc`

`iloc` uses integer positions.

- row 0 = first row
- row 1 = second row
- row -1 = last row

In [7]:

print("First row:")
print(df.iloc[0])

print("\nLast row:")
print(df.iloc[-1])

First row:
Sample       Control
Abs600          0.62
Replicate          1
Name: 0, dtype: object

Last row:
Sample       Treatment B
Abs600              0.77
Replicate              1
Name: 2, dtype: object

## Step 9: Simple Summary Functions

Pandas can quickly summarize numeric data.

In [8]:

print("Mean Abs600:", df["Abs600"].mean())
print("Max Abs600:", df["Abs600"].max())
print("Min Abs600:", df["Abs600"].min())

Mean Abs600: 0.7333333333333334
Max Abs600: 0.81
Min Abs600: 0.62

These functions are useful for lab data because they help us summarize measurements without doing every calculation by hand.

## Step 10: Reading a CSV File

One of the most common Pandas tasks is loading data from a CSV file.

The basic syntax is:

```python
pd.read_csv("file_name.csv")
```

In [9]:

plate_df = pd.read_csv("plate_reader_day1.csv")
plate_df

  Well       Sample  Condition  Abs600
0   A1        Blank      Blank    0.05
1   A2    Control_1    Control    0.62
2   A3    Control_2    Control    0.65
3   B1  Treatment_1  Treatment    0.81
4   B2  Treatment_2  Treatment    0.79
5   B3  Treatment_3  Treatment    0.84

## Step 11: Looking at the CSV Data

After reading a CSV, it is good practice to inspect it right away.

In [10]:

print("Shape:", plate_df.shape)
print("Columns:", list(plate_df.columns))
print()
print(plate_df.head())

Shape: (6, 4)
Columns: ['Well', 'Sample', 'Condition', 'Abs600']

  Well       Sample  Condition  Abs600
0   A1        Blank      Blank    0.05
1   A2    Control_1    Control    0.62
2   A3    Control_2    Control    0.65
3   B1  Treatment_1  Treatment    0.81
4   B2  Treatment_2  Treatment    0.79

## Step 12: Selecting Useful Columns

Plate reader files often contain many columns.
You will usually focus on the columns that matter for your analysis.

In [11]:
print(plate_df[["Well", "Sample", "Abs600"]])

  Well       Sample  Abs600
0   A1        Blank    0.05
1   A2    Control_1    0.62
2   A3    Control_2    0.65
3   B1  Treatment_1    0.81
4   B2  Treatment_2    0.79
5   B3  Treatment_3    0.84

## Step 13: Filtering Rows

We can keep only rows that match a condition.

For example, here we keep rows where the `Condition` is `Treatment`.

In [12]:

treatment_rows = plate_df[plate_df["Condition"] == "Treatment"]
print(treatment_rows)

  Well       Sample  Condition  Abs600
3   B1  Treatment_1  Treatment    0.81
4   B2  Treatment_2  Treatment    0.79
5   B3  Treatment_3  Treatment    0.84

## Step 14: Combining Pandas with Skills You Already Know

Pandas still connects to core Python ideas you already know.

For example:
- variables
- strings
- printing
- indexing
- conditionals

In [13]:

threshold = 0.75
mean_treatment = treatment_rows["Abs600"].mean()

print("Threshold:", threshold)
print("Treatment mean:", mean_treatment)

if mean_treatment > threshold:
    print("Treatment mean is above the threshold.")
else:
    print("Treatment mean is not above the threshold.")

Threshold: 0.75
Treatment mean: 0.8133333333333334
Treatment mean is above the threshold.

# Student Exercises

Complete the exercises below in the empty code cells.

Put your answers directly under each exercise.

**Total Exercise Points: 8 points**, recall 2 points are allocated for reading the handout and running all the code cells. So the total number of points for the lab is **10 points**

## Submission Reminder

Before you submit:
- make sure every code cell has been run
- make sure your output is visible
- double-check spelling in variable names
- make sure you used `import pandas as pd`
- make sure the CSV files are in the same folder as your notebook

## Exercise 1 (1 pt)

Create a dictionary called `small_plate` with the following keys and values:

- `"Sample"`: `["Blank", "Control"]`
- `"Abs600"`: `[0.05, 0.62]`

Convert it into a Pandas DataFrame called `small_df`.

Then print:
1. the whole DataFrame
2. the `Abs600` column

In [42]:
small_plate = {
    "Sample": ['Blank', 'Control'],
    "Abs600": [0.05, 0.62]
}

small_df = pd.DataFrame(small_plate)
print(small_df)
print()
print(small_df['Abs600'])

    Sample  Abs600
0    Blank    0.05
1  Control    0.62

0    0.05
1    0.62
Name: Abs600, dtype: float64

## Exercise 2 (1 pt)

Using the file `plate_reader_day1.csv`:

1. read the file into a DataFrame called `plate_df`
2. print the first 3 rows using `head(3)`
3. print the shape of the DataFrame

In [23]:
plate_df = pd.read_csv('plate_reader_day1.csv')
print(plate_df.head(3))
print()
print('Shape:', plate_df.shape)

  Well     Sample Condition  Abs600
0   A1      Blank     Blank    0.05
1   A2  Control_1   Control    0.62
2   A3  Control_2   Control    0.65

Shape: (6, 4)

# Data Analysis Exercises: Plate Reader CSV Data

A plate reader is a common lab instrument that measures signals from wells in a plate.

In this notebook, the CSV files include:
- `Well` = well location
- `Sample` = sample name
- `Condition` = group label
- `Abs600` = absorbance reading at 600 nm

You will use Pandas to load and analyze this kind of lab data.

## Exercise 3: Basic Plate Reader Summary (3 pts)

Use the file `plate_reader_day1.csv`.

### Part A (1 pt)
Read the CSV file into a DataFrame called `plate1`.

### Part B (1 pt)
Print:
1. the whole DataFrame
2. the list of column names
3. the mean of the `Abs600` column

### Part C (1 pt)
Print:
1. the row for the first well using `iloc`
2. the values from only the `Well` and `Abs600` columns

In [40]:
# Part A
plate1 = pd.read_csv('plate_reader_day1.csv')

# Part B
print('Part B')
print('------')
print(plate1)
print()
print('Columns:', list(plate1.columns))
print()
print('Mean:', plate1['Abs600'].mean())
print()

# Part C
print('Part C')
print('------')
print(plate1.iloc[0])

Part B
------
  Well       Sample  Condition  Abs600
0   A1        Blank      Blank    0.05
1   A2    Control_1    Control    0.62
2   A3    Control_2    Control    0.65
3   B1  Treatment_1  Treatment    0.81
4   B2  Treatment_2  Treatment    0.79
5   B3  Treatment_3  Treatment    0.84

Columns: ['Well', 'Sample', 'Condition', 'Abs600']

Mean: 0.6266666666666666

Part C
------
Well            A1
Sample       Blank
Condition    Blank
Abs600        0.05
Name: 0, dtype: object

## Exercise 4: Filtering and Comparing Groups (3 pts)

Use the file `plate_reader_day2.csv`.

### Part A (1 pt)
Read the CSV file into a DataFrame called `plate2`.

Create:
- `control_df` containing only rows where `Condition` is `"Control"`
- `treatment_df` containing only rows where `Condition` is `"Treatment"`

### Part B (1 pt)
Calculate and print:
1. the mean `Abs600` for the control group
2. the mean `Abs600` for the treatment group

### Part C (1 pt)
Use an `if/else` statement to compare the two means and print:
- `"Treatment mean is higher"` if the treatment mean is larger
- `"Control mean is higher"` otherwise

In [57]:
# Part A
plate2 = pd.read_csv('plate_reader_day2.csv')
control_df = plate2[plate2["Condition"] == "Control"]
treatment_df = plate2[plate2["Condition"] == "Treatment"]

# Part B
control_mean = control_df["Abs600"].mean()
treatment_mean = treatment_df["Abs600"].mean()
print('Control Mean:', control_mean)
print('Treatment Mean:', treatment_mean)
print()

# Part c
if treatment_mean > control_mean:
    print("Treatment mean is higher")
else:
    print("Control mean is higher")

Control Mean: 0.5966666666666667
Treatment Mean: 0.7666666666666666

Treatment mean is higher